#!/bin/bash
export LD_LIBRARY_PATH=/zfsqd1/app/xz-5.2.3/lib/:$LD_LIBRARY_PATH
DIR=`readlink -fe $0`
if [[ -z $DIR ]];then
    DIR=`dirname $0`
else
    DIR=`dirname $DIR`
fi

SAMTOOLS="${DIR}/samtools.exe"
${SAMTOOLS} $@
